#!/bin/bash
# This script installs the Yocto build tools for Ubuntu 22.04 and builds the Yocto builder container image.

print_usage() {
    echo "Usage: $0 [-r|--rebuild] [-h|--help]"
    echo "Options:"
    echo "  -r, --rebuild        Froce rebuild the Yocto builder container image"
    echo "  -h, --help           Show this help message"
    exit 1
}

REBUILD=0
CLEAN=0
# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -r|--rebuild)
            REBUILD=1
            shift
            ;;
        -c|--clean)
            CLEAN=1
            REBUILD=0
            shift
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done
# If the -c or --clean option is specified, clean the build tools directory
# This will remove all files in /opt/yocto, which is where the Yocto build tools are installed
if [[ $CLEAN -eq 1 ]]; then
    echo "Cleaning build tools directory..."
    rm -rf /opt/yocto/*
    echo "Build tools directory cleaned."
    echo "Removing podman image..."
    podman rmi yocto-ubuntu:22.04 
    echo "Podman image removed."
fi

# Check if the build tools have already been installed
if [ -f "/opt/yocto/environment-setup-x86_64-pokysdk-linux" ]; then
    echo "Yocto build tools already installed."
else
    echo "Installing Yocto build tools..."
    # Create the directory if it doesn't exist
    mkdir -p /opt/yocto
    # Download and install the Yocto build tools for Ubuntu 22.04, install them in /opt/yocto, and build the Yocto builder container image.
    wget https://downloads.yoctoproject.org/releases/yocto/yocto-5.0/buildtools/x86_64-buildtools-nativesdk-standalone-5.0.sh \
        && chmod +x x86_64-buildtools-nativesdk-standalone-5.0.sh \
        && ./x86_64-buildtools-nativesdk-standalone-5.0.sh -y -d /opt/yocto \
        && rm x86_64-buildtools-nativesdk-standalone-5.0.sh

    echo "Yocto build tools installed successfully."
fi

# If the -r or --rebuild option is specified, rebuild the Yocto builder container image
if [[ $REBUILD -eq 1 ]]; then
    echo "Rebuilding Yocto builder container image..."
    podman build -t yocto-ubuntu:22.04 . || { echo "Failed to rebuild Yocto builder container image."; exit 1; }    
    exit 0
fi

# Check if the builder container image already exists
ID=$(podman images | grep yocto-ubuntu | awk '{print $3}')
if [ -n "$ID" ]; then
    echo "Yocto builder container image already exists with ID: $ID"
    exit 0
fi

echo "Building Yocto builder container image..."
# Build the Yocto builder container image from the Docker file
podman build -t yocto-ubuntu:22.04 .