#!/bin/bash

# This script installs the Yocto build tools for Ubuntu 22.04 and builds the Yocto builder container image.

# Check if the build tools have already been installed
if [ -f "/opt/yocto/environment-setup-x86_64-pokysdk-linux" ]; then
    echo "Yocto build tools already installed."
else
    echo "Installing Yocto build tools..."
    # Create the directory if it doesn't exist
    mkdir -p /opt/yocto
    # Download and install the Yocto build tools for Ubuntu 22.04, install them in /opt/yocto, and build the Yocto builder container image.
    wget https://downloads.yoctoproject.org/releases/yocto/yocto-5.0/buildtools/x86_64-buildtools-nativesdk-standalone-5.0.sh \
        && chmod +x x86_64-buildtools-nativesdk-standalone-5.0.sh \
        && ./x86_64-buildtools-nativesdk-standalone-5.0.sh -y -d /opt/yocto \
        && rm x86_64-buildtools-nativesdk-standalone-5.0.sh \
        || echo "Failed to download or install Yocto build tools." && exit 1

    echo "Yocto build tools installed successfully."
fi

# Check if the builder container image already exists
ID=$(podman images | grep yocto-ubuntu | awk '{print $3}')
if [ -n "$ID" ]; then
    echo "Yocto builder container image already exists with ID: $ID"
    exit 0
fi

echo "Building Yocto builder container image..."
# Build the Yocto builder container image from the Docker file
podman build -t yocto-ubuntu:22.04 .