#!/bin/bash

print_usage() {
    echo "Usage: $0 [-c|--clean] [-i|--image <image_name>] [-h|--help]"
    echo "Options:"
    echo "  -c, --clean          Clean data from old builds. Can be specified up to 3 times for different levels of cleaning."
    echo "  -i, --image <name>   Specify the image to build (default: pitrac-image-base)"
    echo "  --no-image           Do not run the bitbake build process for the PiTrac image"
    echo "  --build-sdk          Build the SDK"
    echo "  -h, --help           Show this help message"
}

# Default values
CLEAN=0
IMAGE="pitrac-image-base"
BUILD_IMAGE=1
BUILD_SDK=0
# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -c|--clean)
            CLEAN=($((CLEAN + 1)))
            shift
            ;;
        -i|--image)
            IMAGE="$2"
            shift 2
            ;;
        --no-image)
            BUILD_IMAGE=0
            shift
            ;;
        --build-sdk)
            BUILD_SDK=1
            shift
            ;;
        -h|--help)
            print_usage
            exit 1
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Source the environment setup script
. setup-env > /dev/null

if [[ $CLEAN -gt 0 ]]; then
    echo "Cleaning temp directory..."
    rm -rf tmp/
fi

if [[ $CLEAN -gt 1 ]]; then
    echo "Pruning old sstate-cache files..."
    find sstate-cache -type f -mtime +30 -delete
fi

if [[ $CLEAN -gt 2 ]]; then
    echo "Cleaning sstate for all recipes"
    bitbake -c cleanall world
fi

if [[ ! -d "buildlogs" ]]; then
    mkdir buildlogs
fi

timestamp=$(date +%Y-%m-%d_%H:%M:%S)
if [ $BUILD_IMAGE -gt 0 ]; then
    echo "Building image: ${IMAGE}. Build start at {$timestamp}" | tee buildlogs/build_${timestamp}.log

    # Run bitbake and get the return value to ensure it succeeded
    bitbake $IMAGE 2>&1 | tee buildlogs/build_${timestamp}.log
    if [ ${PIPESTATUS[0]} -eq 0 ]; then
        echo "Image build succeeded"
    else
        echo "Image build failed with exit code ${PIPESTATUS[0]}"
        exit ${PIPESTATUS[0]}
    fi
fi

echo "$BUILD_SDK"
if [ $BUILD_SDK -gt 0 ]; then
    echo "Building SDK: ${IMAGE} Build start at {$timestamp}" | tee buildlogs/sdk_build_${timestamp}.log
    bitbake $IMAGE -c populate_sdk 2>&1 | tee buildlogs/sdk_build_${timestamp}.log
    if [ ${PIPESTATUS[0]} -eq 0 ]; then
        echo "SDK build succeeded"
    else
        echo "SDK build failed with exit code ${PIPESTATUS[0]}"
        exit ${PIPESTATUS[0]}
    fi
fi
