#!/bin/bash

BUILDTOOLS=
if [ -d "${BUILDTOOLS_DIR}" ]; then
    BUILDTOOLS="${BUILDTOOLS_DIR}"
else
    BUILDTOOLS="/opt/yocto"
fi

# This script sets up the environment for building a Yocto project.
. ${BUILDTOOLS}
. layers/poky/oe-init-build-env .

